/* Generated by tools/build-product-pages.js. Do not edit by hand. */
var productUrls = {
    "manual-chain-hoist": "manual-chain-hoist.html",
    "manual-lever-hoist": "manual-lever-hoist.html",
    "stainless-steel-chain-hoist": "stainless-steel-chain-hoist.html",
    "marine-anti-corrosion-chain-hoist": "marine-anti-corrosion-chain-hoist.html",
    "spark-proof-chain-hoist": "spark-proof-chain-hoist.html",
    "spark-proof-lever-hoist": "spark-proof-lever-hoist.html",
    "electrical-chain-hoist": "electrical-chain-hoist.html",
    "low-headroom-electric-chain-hoist": "low-headroom-electric-chain-hoist.html",
    "low-headroom-manual-hoist": "low-headroom-manual-hoist.html",
    "manual-push-trolley": "manual-push-trolley.html",
    "manual-gear-trolley": "manual-gear-trolley.html",
    "electrical-trolley": "electrical-trolley.html",
    "wire-rope-winch": "wire-rope-winch.html",
    "electrical-winch": "electrical-winch.html",
    "beam-clamp": "beam-clamp.html",
    "universal-beam-clamp": "universal-beam-clamp.html",
    "vertical-lifting-clamp": "vertical-lifting-clamp.html",
    "horizontal-plate-lifting-clamp": "horizontal-plate-lifting-clamp.html",
    "horizontal-pipe-lifting-clamp": "horizontal-pipe-lifting-clamp.html",
    "bow-shackle-ep2130": "bow-shackle-ep2130.html",
    "bow-shackle-ep209": "bow-shackle-ep209.html",
    "d-shackle-ep210": "d-shackle-ep210.html",
    "pallet-truck": "hand-pallet-truck.html",
    "drum-lifter": "drum-lifter.html",
    "jack": "rack-jack.html",
    "snatch-block": "snatch-block.html",
    "chain": "alloy-steel-lifting-chain.html",
    "wire-rope-clip-u-bolt": "wire-rope-clip-u-bolt.html"
};

function productUrl(id) {
    return productUrls[id] || ('product-detail_01.html?id=' + encodeURIComponent(id));
}
